TBOX-155 Rename CSV columns
Datatamer/tamr-toolbox pull request #69
Opened 2021-11-04 14:47 UTC by ErinCompaan

# ↪️ Pull Request

## ✔️ PR Todo

- [x ] Add documentation
- [x ] Add examples
- [x ] Ensure you are following the practices in the [contributor guide](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit) and [coding_standards](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards)
  * [Use consistent and descriptive name conventions](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit#heading=h.477s36w4rds9) 
  * [Uses google-style docstrings](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Google-style-docstrings)
  * [Uses versioned API/client methods only](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit#heading=h.yv6df99fyrq2)
  * [Avoid global variables](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Avoid-global-variables)
  * [Avoid giant try/catch](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Avoid-giant-try-/-except)
  * [Don't use mutable default variables](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Don%E2%80%99t-use-mutable-default-arguments)
  * [Use a `main()` function in your scripts](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Use-a-%E2%80%9Cmain()%E2%80%9D--function-in-your-scripts)
- [x ] Added/updated testing for this change (ensure you are testing any changes/new code!)
- [ x] Update title to link to TBOX issue (i.e. start pull request title with TBOX-xx) 
- [ ] Approval from first code-reviewer
- [ ] Approval from second code-reviewer (only required if a second reviewer has left comments)
- [ ] Pass all checks

2021-11-05 21:09 UTC, skalish commented on tamr_toolbox/data_io/csv.py
> +    column_name_dict: Optional[dict] = None,
More specific type hint
```suggestion
    column_name_dict: Optional[Dict[str, str]] = None,
```

2021-11-05 21:11 UTC, skalish commented on tamr_toolbox/data_io/csv.py
> +    column_name_dict: Optional[dict] = None,
Feel free to improve type hints in this way on existing code in the files that you're touching as well.

2021-11-05 21:17 UTC, skalish commented on tamr_toolbox/data_io/common.py
> +        full_column_name_dict = {**dict(zip(columns, columns)), **column_name_dict}
A possible alternate statement (not necessary to change)
```suggestion
        full_column_name_dict = {column: column_name_dict.get(column, column) for k in columns}
```

2021-11-24 15:51 UTC, skalish commented on tamr_toolbox/data_io/common.py
> +        full_column_name_dict = {col: column_name_dict.get(col, col) for col in columns}
This line ensures that the order of the entries in `full_column_name_dict` matches the order of the entries in `columns` as desired.  Can you add a comment stating this so it's clear that this is happening (and is intentional)?

2021-11-24 15:56 UTC, skalish requested changes
This looks great!  I think another test case would be ideal, but then it should be ready for approval.

2021-11-24 15:56 UTC, skalish commented on tests/data_io/test_csv.py
> +        ),  # test with columns subset specified
Can you add a case where there are multiple columns renamed, and the order in `columns` and `column_name_dict` conflict?  The result should be that the order in `columns` is obeyed.

2021-11-24 15:58 UTC, skalish commented
As more of an experiment than a requirement, can you locally run `pytest --cov=tamr_toolbox --cov-report=term-missing tests/` and see if any part of your contribution is not covered by tests?

2021-11-24 19:44 UTC, ErinCompaan commented
> As more of an experiment than a requirement, can you locally run `pytest --cov=tamr_toolbox --cov-report=term-missing tests/` and see if any part of your contribution is not covered by tests?

Everything new is covered by tests:
```
tamr_toolbox/data_io/common.py                       59      0   100%
tamr_toolbox/data_io/csv.py                         113     24    79%   84-89, 94-99, 110-120, 178, 253, 265-268, 294-301
```

2021-11-24 20:57 UTC, skalish approved these changes
LGTM

2021-11-29 22:14 UTC, merged